### ISSUE TITLE
Font Size half that of what is defined in the guide

### ISSUE THREAD

**Issue by tiholic** [johngray1965/FlutterZeplinExtension#2]
Flutter plugin

Font size 20sp is changed to 10.0 in the generated styles.

![image](https://user-images.githubusercontent.com/14252381/41397525-20cb8b52-6fd2-11e8-89be-f6f3e05a348e.png)

Please let me know if I am missing anything. Should I be using `textScaleFactor`?

ref:  #119           ```elements.push(`    fontSize: ${(style.fontSize/2).toFixed(1)}`);```

**Comment by johngray1965** [comment]
Yes, I'm aware of that problem.  I'm going to add a option like the react native plugin has so you set the scale in the in plugins settings.

**Comment by johngray1965** [comment]
Actually I pushed a fix, in the code above, it just replaces the 2 with project.densityDivisor.  That should get the proper values.  I've asked Zeplin to push an update.

**Comment by tiholic** [comment]
Thanks you very much @johngray1965. Can you say how long Zeplin might take to update this?
