### ISSUE TITLE
Add style for box

### ISSUE THREAD

**Issue by locxm93** [johngray1965/FlutterZeplinExtension#3]
Hi @johngray1965 !
Thank you for create flutter zeplin extension. 
Currently, This extension don't have style for box.
Could you add style for box, example:
Button, Card, Square, Rectangle (Style: border-color, border-radius, border-width, background,shadow,padding, margin,...)
I hope you can update style for box.
Thank you so much.
Regards.

**Comment by johngray1965** [comment]
I believe we don't currently have the information to do that (I might be wrong).  The designer side plugins (for Photoshop, Sketch and Figma) are being updated to support components.  Right now only Sketch has component support.  Once the other plugins are updated, I'll make a new version that supports Components, I think that'll give you what you want.

**Comment by locxm93** [comment]
@johngray1965 !
I hope you make a new version supports Components soon.
Thank you very much for your contribution.

**Comment by johngray1965** [comment]
The fine folks @ Zeplin have given me access to project that has a bunch of components defined.   I hope to support some of them in the next week or so.  Some more exoteric things may never be supported.

**Comment by johngray1965** [comment]
I requested new version be published.  It support styleGuides and has much better layout support.
