### ISSUE TITLE
After updating the Zeplin to Version 2.5 (717) The  element has no flutter code 

### ISSUE THREAD

**Issue by Abgaryan** [johngray1965/FlutterZeplinExtension#4]

**Comment by johngray1965** [comment]
What element?  I'm just about to do a new round of development on it.  I imagine it'll get straightened out in that, but if you give me more details, that would be helpful.

**Comment by johngray1965** [comment]
I did a fairly radical rewrite, I've asked zeplin to publish the new version.   Fairly sure this will resolve your issue.
