### ISSUE TITLE
Support for layout widgets

### ISSUE THREAD

**Issue by Levi-Lesches** [johngray1965/FlutterZeplinExtension#5]
Consider the following ("Member" page from Figma sample project): 

![Screenshot (13)](https://user-images.githubusercontent.com/20747538/61508555-667c2780-a9b8-11e9-8337-116fb72022f8.png)

Here, by rolling over the white rectangle, the expected output would be something like: 
```dart
Row (
  children: [
    Text ("THE\nART\nMUSEUM"),
    Container(width: 40),  // This might be a good time to use Spacer() BTW
    Text ("Become a Member", textStyle: TextStyle (color: Colors.red)),
    Container (width: 40),
    Icon (Icons.menu) // also not yet supported but I understand
  ]
),
```

Clicking on each of those individual elements works perfectly, but the whole white rectangle will just select the whole screen which defaults to `Container()`. How hard would Layout widgets be? 

Overall, this extension looks really interesting, and, if it works, it can bring the simplicity of Flutter to those who have a phobia of the keyboard. With some time, I hope to be able to help you with this, if you would like.

**Comment by johngray1965** [comment]
On another note, if you can give me access to your zeplin project, I'll test to see if generating for it correctly.

**Comment by johngray1965** [comment]
Another thing to note, won't do anything good with the icon.  We don't appear to very good meta data there.  We'll just create a container there that's sized and placed properly.  You'll just need to add the icon as a child of that container.

**Comment by Levi-Lesches** [comment]
I see it starts to work in limited cases. Zeplin (for me) doesn't let me click that many things, only really the overall frame (which defaults to a white container). 

I can share the project with you(it's really only the Figma sample project exported to Zeplin). What's your email?

**Comment by johngray1965** [comment]
my username is johnatagoranet, will that do?  I hate to put my email here.  It's open to the public.

**Comment by Levi-Lesches** [comment]
That didn't work, but I get not wanting to have your email out there. If you really want to test, just go to the sample Figma project (the art gallery one) and export it to Zeplin

**Comment by johngray1965** [comment]
I just put out 1.30, see how that looks.

**Comment by Levi-Lesches** [comment]
I haven't had time to review it, but if you just copy and paste the code from the above screen, it doesn't render. Like, I see the title and upper left text, but nothing else... And this is after removing all non-existent fonts.

**Comment by johngray1965** [comment]
In the example above, about all you'll get is the title and upper left text, almost everything else are images.  We don't get enough info for the images to do much of anything with them.  I just create container that are the right size and position.   This going to make production code for you.  It'll create a good starting point.

**Comment by Levi-Lesches** [comment]
So basically, Zeplin needs to provide much more resolution (at least when importing from Figma)

**Comment by Levi-Lesches** [comment]
If that's the case, I'm fine if you want to close this issue.

**Comment by johngray1965** [comment]
I heard from some @ Zeplin that's that they add more support in the future for images.  When that is done, I'll try to add the support to the extension.  So I'll close this issue now.
