### ISSUE TITLE
Variables name with special chars

### ISSUE THREAD

**Issue by dariof28** [johngray1965/FlutterZeplinExtension#8]
If the Style or the Color have a name with slashes or more than one dash the generated code will be an invalid variable name:
 
**"H1 / middle / 01-primary"**
```dart 
static const h1/Middle/1Primary = const TextStyle(...)
```
**"callout / middle / 04-06-white"**
```dart
static const callout/Middle/46-White = const TextStyle(...)
```

**Comment by johngray1965** [comment]
See if 1.4.0 fixes your issue. Sorry for the delay.
